//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantReserv.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class General
    {
        public int Id { get; set; }
        public string Header { get; set; }
        public string HeaderAddress { get; set; }
        public string HeaderText { get; set; }
        public string Story { get; set; }
        public string Quote { get; set; }
        public string Newsletter { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Facebook { get; set; }
        public string Twitter { get; set; }
        public string Instagram { get; set; }
        public string LinkedIn { get; set; }
        public string HeaderPicture { get; set; }
        public string OrderPhone { get; set; }
        public string Logo { get; set; }
        public string LogoWhite { get; set; }
        public string Favicon { get; set; }
    }
}
