//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantReserv.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statistic
    {
        public int Id { get; set; }
        public string Image { get; set; }
        public string Text { get; set; }
        public Nullable<int> DataCount { get; set; }
        public string DataText { get; set; }
    }
}
